# version: '3'
services:
  web:
    user: root
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
